data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vq19475.us-east-2.aws
      user: SAIPRASADDONAKANTI26
      password: "Enter your password"   # ← fix it here
      role: dbt_role
      warehouse: dbt_wh
      database: dbt_db
      schema: dbt_schema
      threads: 10
